# 下载基础镜像
FROM registry.cn-hangzhou.aliyuncs.com/nacl-public/torchserve:0.11.0-gpu as builder

# 使用Root用户
USER root

# 安装 ffmpeg wget p7zip-full
RUN apt-get update && apt-get install -y ffmpeg wget p7zip-full

# 设置工作目录
WORKDIR /app

# 复制文件到 /app 目录
COPY . ./

# 下载模型
# RUN wget https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/all-models.7z -O ./all-models.7z
RUN wget https://gh.ddlc.top/https://github.com/jianchang512/ChatTTS-ui/releases/download/v1.0/all-models.7z -O ./all-models.7z

# 解压模型 并 删除压缩包
RUN 7z x ./all-models.7z -o./ && rm ./all-models.7z
# 创建
RUN mkdir -p /app/asset/tokenizer

# 给 asset 赋权 777
RUN chmod -R 777 /app/asset

# 下载 tokenizer
# RUN wget -O /app/asset/tokenizer/tokenizer.json https://huggingface.co/2Noise/ChatTTS/resolve/main/asset/tokenizer/tokenizer.json
# RUN wget -O /app/asset/tokenizer/special_tokens_map.json https://huggingface.co/2Noise/ChatTTS/resolve/main/asset/tokenizer/special_tokens_map.json
# RUN wget -O /app/asset/tokenizer/tokenizer_config.json https://huggingface.co/2Noise/ChatTTS/resolve/main/asset/tokenizer/tokenizer_config.json
RUN wget -O /app/asset/tokenizer/tokenizer.json https://hf-mirror.com/2Noise/ChatTTS/resolve/main/asset/tokenizer/tokenizer.json
RUN wget -O /app/asset/tokenizer/special_tokens_map.json https://hf-mirror.com/2Noise/ChatTTS/resolve/main/asset/tokenizer/special_tokens_map.json
RUN wget -O /app/asset/tokenizer/tokenizer_config.json https://hf-mirror.com/2Noise/ChatTTS/resolve/main/asset/tokenizer/tokenizer_config.json

# 安装环境
RUN pip install -r docker_gpu_requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple